blank_issues_enabled: false
contact_links:
  - name: Anexia contact form
    url: https://anexia.com/en/company/contact
    about: "General contact form, or use e-mail: opensource@anexia-it.com to ask contribution related questions."