name: Dependency check

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run depscheck
        run: make depscheck
