name: Dependency check

on:
  push:
    branches:
    - main
    - 'release/**'
  pull_request:
    branches:
    - main

jobs:
  deps_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Dependency check
        run: make depscheck
