name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run unit tests
      run: make test
  test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run integration tests
      run: make testacc
